### ISSUE TITLE
账号登录失败，获取bdstoken失败

### ISSUE THREAD

**Issue by wuzhishao** [mabDc/eso#10]
版本号：3.5.3
系统：win10专业版：版本：19041
笔记本型号：HP HP Pavilion Notebook

操作步骤;
1.直接使用ie内核扫码登录，提示“账号登录失败，获取bdstoken失败”
2.下载Webkit内核扫码登录，提示“账号登录失败，获取bdstoken失败”
3.（ie内核、Webkit内核）第三方登录，提示“账号登录失败，获取bdstoken失败”

麻烦大大，有时间可以看看，我实在不知道如何找到正确的进入方式

**Comment by mabDc** [comment]
抱歉，我不明白你是什么问题。账号登录指的是什么

**Comment by wuzhishao** [comment]
### 
![image](https://user-images.githubusercontent.com/22510367/96365280-11f2c980-1172-11eb-9955-da001455f1c2.png)

**Comment by wuzhishao** [comment]
> 抱歉，我不明白你是什么问题。账号登录指的是什么

就是网盘登录

**Comment by mabDc** [comment]
网盘登录又是什么？
