### ISSUE TITLE
Because eso depends on file_chooser from git which requires SDK version >=2.12.0-0 <3.0.0, version solving failed.

### ISSUE THREAD

**Issue by jinfagang** [mabDc/eso#12]
Because eso depends on file_chooser from git which requires SDK version >=2.12.0-0 <3.0.0, version solving failed.

最新的Flutter 也才 Dart 2.10 怎么才能升级到 2.12 这个需要的？

**Comment by mabDc** [comment]
我这两天没尝试编译了。你这个提示说的插件file_chooser的问题吧，他是谷歌自己团队在维护，你去他那边看看

**Comment by jinfagang** [comment]
@mabDc 感谢回复。我两边都提了一个issue，现在不知道怎么跳过去这个bug了，不知道其他童鞋是如何操作的？因为最新的flutter只有2.10且为最新

**Comment by mabDc** [comment]
1,使用他那边的历史版本
或者2,你clone后本地修改再引用
或者3,你更新到flutter的master分支，
你可以选择其中某个方案

**Comment by mabDc** [comment]
有问题欢迎继续询问，be easy

**Comment by jinfagang** [comment]
我切换到master解决了，谢谢大佬
