### ISSUE TITLE
Sub project for each kind of Viewer

### ISSUE THREAD

**Issue by winterdl** [mabDc/eso#17]
Each kind of content type need alot effort to create a best viewer for that content type, so we need sub project to focus only one type of content type.

- novel viewer
- manga viewer
- audio
- video

**Comment by mabDc** [comment]
虽然这么说没错，单独做一个内容可以做到更好，但是实现单一功能的类似的app已有很多，我包容如此多的功能只是不想安装太多的app。

**Comment by winterdl** [comment]
I know, my idea is about sub module, one app includes all features, but each feature is about one sub project or module. 
Thank you.

**Comment by mabDc** [comment]
哦，是我误会了。但是你说的sub moudle其实我并不懂。我写代码是业余，几乎没学。很多地方因我知识储备不够，没考虑好，我自己也觉得很遗憾。

**Comment by mabDc** [comment]
其实，我还是想知道，按你想法，我该做什么。若是可行，我不妨一试。
