### ISSUE TITLE
PC端视频不能播放，不能解析

### ISSUE THREAD

**Issue by duoremi** [mabDc/eso#23]
![0859dc71cc64a5a4755a525c72fb25b](https://user-images.githubusercontent.com/35366333/108932015-9b1b8f00-7683-11eb-86f2-187451b26816.png)

**Comment by mabDc** [comment]
嗅探需安装测试版的edge浏览器

**Comment by mabDc** [comment]
https://www.microsoftedgeinsider.com/zh-cn/

**Comment by mabDc** [comment]
https://developer.microsoft.com/zh-cn/microsoft-edge/webview2/#download-section

这个地址可以单独安装runtime

**Comment by mabDc** [comment]
https://github.com/mabDc/eso/releases/tag/ESO-1.21.06-12106
