### ISSUE TITLE
PC端视频解析失败

### ISSUE THREAD

**Issue by qq984876303** [mabDc/eso#24]
视频解析失败，麻烦修复下

**Comment by mabDc** [comment]
嗅探需安装测试版的edge浏览器

**Comment by mabDc** [comment]
https://www.microsoftedgeinsider.com/zh-cn/

**Comment by mabDc** [comment]
https://developer.microsoft.com/zh-cn/microsoft-edge/webview2/#download-section

这个地址可以单独安装runtime

**Comment by qq984876303** [comment]
能不能具体教一下怎么搞

**Comment by mabDc** [comment]
自行安装

**Comment by mabDc** [comment]
https://github.com/mabDc/eso/releases/tag/ESO-1.21.06-12106
