### ISSUE TITLE
Video play failed.

### ISSUE THREAD

**Issue by liudonghua123** [mabDc/eso#25]
I tried to open a video in `97看片`, then it failed with the following errors.

![image](https://user-images.githubusercontent.com/2276718/110420301-f878fc80-80d5-11eb-8b77-f2bc6ef81b88.png)

```log

[12:50:51] 正在解析 请等待...
[12:50:53] 失败
PlatformException(FlutterWebviewException, Failed at CreateCoreWebView2Environment, null, null)
#0      APIFromRUle.content (package:eso/api/api_from_rule.dart:398)
<asynchronous suspension>
#1      VPDProvider.parse (package:eso/page/video_page_desktop.dart:182)
<asynchronous suspension>
```

I have edge canary installed.

**Comment by mabDc** [comment]
`CreateCoreWebView2Environment`这个错误需要安装嗅探插件

**Comment by liudonghua123** [comment]
> `CreateCoreWebView2Environment`这个错误需要安装嗅探插件

我确实已经安装了 ms edge canary (默认安装在 `%LOCALAPPDATA%\Microsoft\Edge SxS` )，不知道这个程序是如何查找 edge 内测版的.

**Comment by mabDc** [comment]
程序是按照这个说明整的 https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/win32 
用的win32 (c++)。

**Comment by mabDc** [comment]
他的说明是这样的
> Prerequisites
> Ensure you install the following list of pre-requisites before proceeding.
> 
> WebView2 Runtime or any Microsoft Edge (Chromium) non-stable channel installed on supported OS (currently Windows 10, Windows 8.1, and Windows 7).
> 
>  Note
> 
> The WebView team recommends using the Canary channel and the minimum required version is 82.0.488.0.
> 
> Visual Studio 2015 or later with C++ support installed.

**Comment by mabDc** [comment]
如果你对实现感兴趣，也可以参考

https://github.com/ekibun/flutter_webview

**Comment by liudonghua123** [comment]
我想起来之前安装的是32位的`Microsoft Edge (Chromium) non-stable channel`，因为flutter是64位的程序，可能用不了32位的dll，安装了64位的了，现在没有报这个错，但是报其他错误了，类似于下面的错误，那应该是`WebView2`已经调用解析了，可能是规则还有问题。

```

[14:03:45] 正在解析 请等待...
[14:04:06] 失败
Webview Call timeout 8 seconds after page completed.
#0      APIFromRUle.content (package:eso/api/api_from_rule.dart:398)
<asynchronous suspension>
#1      VPDProvider.parse (package:eso/page/video_page_desktop.dart:182)
<asynchronous suspension>
```

**Comment by mabDc** [comment]
对。确实用不了32的。这个错误是嗅探超时了。换个吧
