### ISSUE TITLE
Update the code that was used to build apk

### ISSUE THREAD

**Issue by winterdl** [mabDc/eso#29]
The source code from repo may not the code that was used to built demo apk. Please update the code.

 ```
 static Future<List<DiscoverMap>> discoverMap(String originTag) async {
    if (originTag != null) {
      final api = apiMap[originTag];
      if (api != null) return api.discoverMap();
      return <DiscoverMap>[
        for (var i = 0; i < 10; i++)
          DiscoverMap("tab$i", <DiscoverPair>[
            for (var j = 0; j < 3; j++) DiscoverPair("class$j", ""),
          ])
      ];
    }
    return <DiscoverMap>[];
  }
```

Thank you.

**Comment by mabDc** [comment]
what do you want to find? something like data source or api? the available api was listed from `apiMap`, that is `lib/api/jsonholderxx.dart`. but parsing other sources was not here. you need according to impl `API` and handle by yourself.

**Comment by winterdl** [comment]
The apk demo features were completely diffirent with the source code that tagged the same version. It will be wasted time to read the fake source code.

**Comment by mabDc** [comment]
you mentioned `demo` times, where's demo?

if you have a look at file `pubspec.yaml`, you may find line 4: `1.20.14+12014` ( `20` means year 2020) and [ESO-1.20.14-120014](https://github.com/mabDc/eso/releases/tag/ESO-1.20.14-120014) in release tag list, they are truth the same between code and app because the code is the all thing to build app.

but what do you want to find? what is your focus? you need tell to me or i can't get your points.

**Comment by winterdl** [comment]
I want to find the novel reader view that use text_composion in 1.21.x apk, but the source code in release tags was 1.20.x only. It is good if you update the source code to 1.21.x or text_composion to latest update. Anyway this is a good app, take it up. Thank you.

**Comment by mabDc** [comment]
but why issuse here? as you ask for `text_composion`, it is in `https://github.com/mabDc/text_composition`. its code will update today or tommorrow after i test for same color or width values (shadow width and shadow color and paddings and so on)

**Comment by mabDc** [comment]
@winterdl check at https://github.com/mabDc/text_composition/releases/tag/0.0.5

**Comment by winterdl** [comment]
Thank you very much!
