### ISSUE TITLE
很棒的app，提个建议。

### ISSUE THREAD

**Issue by YeFei572** [mabDc/eso#31]
下载了作者的app，功能很强大，只是源可能不是最新有些不能用， 不过就技术的运用来讲已经很不错了。
特别佩服作者自己封装的视频播放器，UI完美，体验非常丝滑，功能也比较强劲。

看代码作者应该用了好几个插件不太满意最后自己封装的吗？
能不能出个插件方便大众呢。目前说真的视频播放器插件都很烂。烂透了，希望作者这个插件能出来。谢谢

**Comment by mabDc** [comment]
视频界面和控制都在这个文件里，上面是布局，底下是交互，拖动手势在下面这段代码里。（我写的没有章法，没理论基础，纯想象了）
https://github.com/mabDc/eso/blob/fe1f4a1c7aed848518f852e4ad1d383edd901350/lib/page/video_page_refactor.dart#L847
