### ISSUE TITLE
[功能跟反馈]小说阅读设置能否增加锁屏时间设置为从不,以及往右滑动翻页功能问题.

### ISSUE THREAD

**Issue by shinji-ikari** [mabDc/eso#39]
1.希望能增加锁屏时间设置
原因是原本手机默认的锁屏时间太短30秒左右就会自动锁屏,翻了几圈设置没有看到有设置从不锁屏的功能,请问是我看漏了还是的确没有这个功能?(应该没眼瞎到这地步吧....)

2.往 ~~左~~ 右滑动翻页功能
有启用`单手模式`,也就是即便点击左侧也是下一页,所以想返回上一页的话得往~~左~~ 右 翻页
会觉得有问题其实是跟第一个锁屏时间有关的,时不时会因为还没看完就接近熄屏,需要点一下界面,结果触发了翻页,这就需要往~~左~~ 右翻页来返回上一页,但是翻页发现有个问题,需要滑动到一定地步而不是仅仅往~~左~~ 右滑动这个动作就能返回上一页,这就导致需要大幅度的滑动或者要重复往~~左~~ 右滑动两三次才能成功.

软件版本是 1.22.3
版号 14203
包名  com.mabdc.eso

**Comment by mabDc** [comment]
收到。
常亮的话，视频界面应该是自动开启了，文字界面原来有个比较丑的界面，去年改了动画和排版效果，亮度和常亮漏加了，我看看加回来
左滑和右滑应该手势识别不精准，滑动是超过屏幕5%宽度才生效

**Comment by mabDc** [comment]
![Screenshot_2022-03-16-09-56-40-485_com.mabdc.eso.jpg](https://user-images.githubusercontent.com/19526331/158501388-9d33ef34-36ea-4cc2-b467-fce39fdd20df.jpg)

(有段时间是这样的界面

**Comment by shinji-ikari** [comment]
> (有段时间是这样的界面

这界面感觉还行啊,也没觉得丑.... 其实原本这样一个小弹框,可以轻松设置一些常用的,然后添加一个`更多设置` 然后点完直接跳设置界面,左上角有个返回可以设置了之后返回到原本的小说页面那里, 而不用整个把设置都变成弹框出来可能还更好点.hmmm也可能是我习惯了这样的设置界面吧.

滑动>5%, 才这么点宽度的话应该随手划一下都有了....至少在别的软件上没发现有划不动的问题.主要是体验在不能快速滑动.得按下去了然后缓慢一点往右边滑动那样才能保证一次性成功.
界面上看起来就有点像是那种要把上一页明显有拉出来并且拉到一定幅度之后再松手才能正常返回上一页这样.

感谢解答, 辛苦了~

**Comment by mabDc** [comment]
前段时间已添加常亮和亮度调节  新版本已上传

**Comment by shinji-ikari** [comment]
好的,抱歉现在才回来看到有更新_(:з」∠)_.已经更新到最新版了.
