### ISSUE TITLE
很想学习一下规则解析，不知是否会开源？

### ISSUE THREAD

**Issue by nowexhas** [mabDc/eso#4]
发现规则解析没有，很想学习一下是如何处理的，不知是否会开源？谢谢。

**Comment by mabDc** [comment]
规则解析部分你可以按自己想法做。

**Comment by mabDc** [comment]
> 发现规则解析没有，很想学习一下是如何处理的，不知是否会开源？谢谢。

暂无计划

**Comment by nowexhas** [comment]
～～没有规则解析也用不了，固定静态数据，以为能学习一下了呢。不过还是支持！

**Comment by mabDc** [comment]
> ～～没有规则解析也用不了，固定静态数据，以为能学习一下了呢。不过还是支持！

解析部分我打算自己维护的。

其实解析只是数据来源的一个手段，还有很多办法可以实现，你甚至可以自己找数据接口或者用我四月底的写法直接内置，或者本地，都可以。用户不会关心数据怎么来的，只看最后结果的。

如果你看我readme列出的功能列表就会发现，列出来的功能和这部分没关系，用户用的只是这些功能。

**Comment by mabDc** [comment]
@nowexhas 对规则有兴趣可以看或者编译这个内置规则的旧版本https://github.com/mabDc/eso/tree/c777db9dc3c6dc5094e639ccc9af1ffd56441a34

**Comment by mabDc** [comment]
参考`/api/json_placeholder.dart`和`/api/json_placeholder_photo.dart`就可以自行添加数据源
