### ISSUE TITLE
更换阅读器背景实时更新

### ISSUE THREAD

**Issue by DouSN** [mabDc/eso#45]
一般小说阅读器更换字体和阅读器背景后都是当前页面就生效，请问有没有办法实现这个功能

**Comment by mabDc** [comment]
有需求当然可以做。你把页面清空重新画就是了，性能的话，耗时应该不到50ms

**Comment by mabDc** [comment]
你也可以用整页替换，比如
navigator of context replace
性能大概会差一点

**Comment by DouSN** [comment]
> 

感谢回复， 我水平太菜了，可以请教下在代码哪里进行清空吗，非常感谢

**Comment by mabDc** [comment]
手机上很难说，你觉得不好搞就刷新整个正文页，用replace，相当于重新打开正文页。
想认真搞的话就看这里
![Screenshot_2022-04-11-23-45-09-677_com.github.android.jpg](https://user-images.githubusercontent.com/19526331/162779709-80b2e339-8924-4ac8-a71c-bb3d2c623150.jpg)

**Comment by mabDc** [comment]
重新去init应该可以

**Comment by DouSN** [comment]
非常感谢
