### ISSUE TITLE
windows项目无法生成，似乎是有文件没有上传，

### ISSUE THREAD

**Issue by PornhuBox** [mabDc/eso#5]
generated_config.cmake
ephemeral文件夹也不存在，不太清楚这几个文件干嘛的，还望解答

**Comment by mabDc** [comment]
我使用最新master分支可以编译。请提供更详细信息。

**Comment by PornhuBox** [comment]
你好，我换用idea开发后，发现最新版里面 flutter的Icons中无法生成 ,报错地点修改如下
位于lib\page\setting下的font_family_page.dart 54行，原为Icon(Icons.add_outlined),,  我改为了Icon(Icons.add),
位于lib\page下的search_page.dart 116行，原为icon: Icon(Icons.close_outlined, size: 18), 我改为了icon: Icon(Icons.close, size: 18),
最新版的Icons里面outlined不用加后缀了应该是

**Comment by mabDc** [comment]
我没有尝试用vs编译。我是命令行输入`flutter run windows -v`和`flutter build windows -v`运行和编译的。我用的昨天的flutter master版本，没有报错。

**Comment by mabDc** [comment]
我安装的visual studio社区版，仅安装c++桌面开发。按照`flutter doctor -v`提示来安装

**Comment by PornhuBox** [comment]
好的，我继续研究下

**Comment by mabDc** [comment]
> generated_config.cmake
> ephemeral文件夹也不存在，不太清楚这几个文件干嘛的，还望解答

@PornhuBox 你应该先尝试空项目在windows下编译成功，先考虑你开发环境安装问题。
我的windows文件夹是前几天刚删掉，用`flutter create .`重新生成的。

**Comment by PornhuBox** [comment]
恩恩，应该是我的开发环境没有安装完全，初次接触flutter，看了一下可能是window端flutter-desktop-embedding没有配置

**Comment by PornhuBox** [comment]
把环境重新弄了一下，已经成功跑起来了，谢谢作者大大指导~
