### ISSUE TITLE
大佬能留个联系方式吗？

### ISSUE THREAD

**Issue by chenyang351** [mabDc/eso#51]
flutter 新手，最近搞一个阅读器的项目，有偿请教一些问题

**Comment by mabDc** [comment]
联系方式这里不就有吗，比如

https://github.com/mabDc/eso/blob/773a94b318b7dd09d8b4a28995b694ca732dbeb7/lib/page/setting/about_page.dart#L248-L257

https://github.com/mabDc/eso/blob/773a94b318b7dd09d8b4a28995b694ca732dbeb7/lib/page/setting/auto_backup_page.dart#L276-L276

Gitter Chatroom https://gitter.im/mabDc/eso

**Comment by chenyang351** [comment]
@mabDc  嗯嗯，加你Q了，麻烦通过下
