### ISSUE TITLE
导入zyplayer规则后，没有影视资源的名称，简介等信息

### ISSUE THREAD

**Issue by yxxyun** [mabDc/eso#73]
导入zyplayer规则后，没有影视资源的名称，简介等信息。
![20230908093903](https://github.com/mabDc/eso/assets/107192/45631a85-7224-4aa6-8bc2-c65e8635760c)

**Comment by mabDc** [comment]
这个规则用的是一个固定模板。是挺早的时候写的，很久没有修订。是xpath写法问题，改成`/html()`方法可以提取，即名称是`//name/html()##.*\[|\].*`，简介是`//des/html()##.*\[|\].*`。你试试看。我的结果如图。

![Screenshot_2023-09-08-10-23-39-738_com.mabdc.eso.jpg](https://github.com/mabDc/eso/assets/19526331/b0e695f9-67bf-4d6d-a607-ffb979fe3359)

**Comment by mabDc** [comment]
搜索也是如此修改

**Comment by mabDc** [comment]
新版本已经解决
