### ISSUE TITLE
有办法真正的全屏吗？以及一些功能建议

### ISSUE THREAD

**Issue by gloryandel** [mabDc/eso#76]
1. 目前只能实现窗口最大化和应用内全屏，设计上允许全屏吗？
2. 希望添加源校验功能
3. 希望增加调用第三方播放器功能
4. 字体很奇怪，有的黑体，有的常规。很像字体缺失

难以想象居然有支持全平台的软件，大佬666

**Comment by mabDc** [comment]
1有系统全屏呀
2是个需求，尚未动工
3也有呀，要选择播放器exe文件
4字体问题需要比较繁琐的设置。应用内有选项可以试试，正文和界面单独设置。

**Comment by gloryandel** [comment]
> 1有系统全屏呀 2是个需求，尚未动工 3也有呀，要选择播放器exe文件 4字体问题需要比较繁琐的设置。应用内有选项可以试试，正文和界面单独设置。

1全屏：目前 Win11 上点了全屏，仅仅应用窗口的内部控件消失，窗口大小不变，仍然保留最大化那一栏。。。
其余了解了

规则中可以实现弹出验证码输入框吗？如http://taoju.tv/indexs.html有搜索验证码😅

**Comment by mabDc** [comment]
你好。有点麻烦的。现在的版本没有写这个功能的。
