### ISSUE TITLE
使用TextComposition加载章节不正常问题

### ISSUE THREAD

**Issue by dcupivnjyft191** [mabDc/eso#78]
遇到问题：使用TextComposition做仿真翻页。在章节内容较短，只有一页两页的时候，加载下一章节不正常。有时候需要往回翻一页才会可以继续往下。或者是翻到下一章很卡。
我使用提供的demo来做测试，修改生成的内容长度，可以复现问题。
```dart
TextCompositionPage(
                  controller: TextComposition(
                    config: config,
                    loadChapter: (index) => Future.delayed(Duration(milliseconds: 100))
                        .then((value) => List.generate(
                            1 + math.Random().nextInt(2),
                            (i) =>
                                "chapter $index, " +
                                "paragraph $i. " * math.Random().nextInt(12))),
                    chapters:
                        List.generate(1234, (i) => "chapter $i, chapter name"),
                    endings: endings,
                    percent: 0.000001,
                    onSave: (TextCompositionConfig config, double percent) {
                      // Global.prefs.setString(TextConfigKey, config);
                      // searchItem.durContentIndex = (percent * NovelContentTotal).floor();
                      print("save config: $config");
                      print("save percent: $percent");
                    },
                    menuBuilder: (textComposition) {
                      return Container();
                    },
                  ),
                )
```

**Comment by mabDc** [comment]
这个问题我也遇到。有点懒。我没仔细看怎么解决。以为不是太严重的bug。

另，明年新版本引擎应该会解决排版的两端对齐问题。大概不需要这样计算空白

**Comment by mabDc** [comment]
对了，感谢反馈

**Comment by dcupivnjyft191** [comment]
> 这个问题我也遇到。有点懒。我没仔细看怎么解决。以为不是太严重的bug。
> 
> 另，明年新版本引擎应该会解决排版的两端对齐问题。大概不需要这样计算空白

嗯嗯，我的用途是显示笔记，一般内容都比较简短，所以这个问题就很明显了。期待新版！也感谢你的开源项目，对我帮助非常大！是仿真翻页效果做得最好的项目了！

**Comment by mabDc** [comment]
两端对齐是flutter排版的问题，一直需要自己计算。已经有人解决了这个问题，看代码是否已经合并进去，之后flutter里按理不用重新计算空白填充。我说的引擎指这个。

其二，单页内容下一章节不自动加载问题，我是第二页才添加下一章到队列里。你可以看下修改到在第一页加载后就延迟加载下一章。

其三，笔记？你是阅读笔记内容？编辑的部分我写不好。我有个项目是笔记来的。名称带note。

**Comment by dcupivnjyft191** [comment]
> 两端对齐是flutter排版的问题，一直需要自己计算。已经有人解决了这个问题，看代码是否已经合并进去，之后flutter里按理不用重新计算空白填充。我说的引擎指这个。
> 
> 其二，单页内容下一章节不自动加载问题，我是第二页才添加下一章到队列里。你可以看下修改到在第一页加载后就延迟加载下一章。
> 
> 其三，笔记？你是阅读笔记内容？编辑的部分我写不好。我有个项目是笔记来的。名称带note。

非常感谢。我尝试了加载第一页后延迟加载下一章。实际体验快速切换翻页会有比较明显的顿挫感。
由于我的需求不会加载非常大的文件内容。所以我修改为初始化的时候一次性加载所有章节，实际体验效果更好。
我是希望做到书籍一样的笔记查看效果。目前我也是新开一个页面来进行编辑，没办法直接编辑。

**Comment by mabDc** [comment]
可以的。适合自己的方案就好。确实计算的消耗总要有个地方给它用。优化也没有止境。实战，合适，能接受也好。
