### ISSUE TITLE
建议添加dav云同步

### ISSUE THREAD

**Issue by chenccf** [mabDc/eso#8]
。。。。。

**Comment by mabDc** [comment]
在计划中。云同步前要先弄好每日自动备份。

**Comment by mabDc** [comment]
已添加完成。

**Comment by chenccf** [comment]
你们是什么软件来着？我都忘记了🌚

在 2021年1月14日星期四，西红柿大芝麻 <notifications@github.com> 写道：

**Comment by chenccf** [comment]
安卓8系统滑动声音大小没效果
